name: Phomemer
description: "Home Assistant Add-on: Phomemer"
url: "https://github.com/wuschLOR/hass-phomemer/tree/main/phomemer"
version: "0.1.21"
slug: phomemer
init: false
host_network: true

arch:
  - amd64

schema:
  PHOMEMO_BT_MAC: "str"

ports:
  8001/tcp: 8001

ports_description:
  8001/tcp: Web interface
