name: Phomemer
version: "0.1.3"
slug: phomemer
description: 'Home Assistant Add-on: Phomemer'
url: "https://github.com/wuschLOR/hass-phomemer/tree/main/phomemer"
arch:
  - amd64
init: false
schema:
  PHOMEMO_BT_MAC: "str"
ports:
  8000/tcp: 8000



